name: "HOTFIX to Workshop"

on:
  push:
    branches:
      - main

jobs:
  hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: gandarez/check-pr-body-action@v1.0.3
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          contains: '`hotfix`'
          appID: 108600
          #publishedFileID -- workshop ID
          publishedFileID: 2909488957
          #changelog: 'log of changes'
          path: Contents
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD  }}
